/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type zh_CNMessage from '../locales/zh_CN/messages.json';
import type zh_TWMessage from '../locales/zh_TW/messages.json';
import type enMessage from '../locales/en/messages.json';
import type pt_BRMessage from '../locales/pt_BR/messages.json';

export type MessageKey = keyof typeof zh_CNMessage &
  keyof typeof zh_TWMessage &
  keyof typeof enMessage &
  keyof typeof pt_BRMessage;

export type DevLocale = 'zh_CN' | 'zh_TW' | 'en' | 'pt_BR';
